spring.application.name=banking_sys

spring.datasource.url=jdbc:mysql://localhost:3306/banking_system
spring.datasource.username=root
spring.datasource.password=trisha1504

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true